### ISSUE TITLE
Operaciones Basicas de los Sistemas Numericos

### ISSUE THREAD

**Issue by YulianaMorales18** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-YulianaMorales18#1]
[Operaciones Basicas Claudia Yuliana Morales Hernandez 1AS (1).pdf](https://github.com/user-attachments/files/16859967/Operaciones.Basicas.Claudia.Yuliana.Morales.Hernandez.1AS.1.pdf)

**Comment by A-Lorely-Z** [comment]
Portada: 25/25
Procedimiento:25/25
Figuras, ilustraciones y fotografías:25/25
Resultados y conclusiones:25/25
 Final: 100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
